10.1)
try:
    x=10/0
except Exception as e:
    print("an error occurred:",str(e))

output:
an error occurred: division by zero
----------------------------------------------------
10.2)
try:
    num=int(input("enter a number"))
    result=10/num
    print("result:",result)
except ValueError:
    print("Error : invalid input ! please enter a valid number.")
except zerodivisionError:
    print("error: division by zero!")

output:
enter a number 2
result: 5.0
----------------------------------------------------
10.3)
try:
    num=int(input("enter a number:"))
    result = 10/num
except valueerror:
    print("error:invalid input! please enter a valid number.")
except zerodivisionerror:
    print("error:division by zero!")
else:
    print("result:",result)
    
    
output:
enter a number:2
result: 5.0
----------------------------------------------------
10.4)
try:
    file=open("my file.txt",'r')
except IoError:
    print("error: unable to read the file !")
finally:
    file.close()

output:
Traceback (most recent call last):
  File "D:/24FFMCA035/Python lab (24FFMCA035)/program 10/10.4.py", line 6, in <module>
    file.close()
NameError: name 'file' is not defined
----------------------------------------------------
10.5)
try:
    x=int(input('enter a number upto 100:'))
    if x<100:
        raise valueerror(x)
except valueerror:
    print(x,"is out of allowed range")
else:
    print(x,"is within the allowed range")

output:
enter a number upto 100:123

123 is within the allowed range